services:
  my-backend-car-project:
    build: .
    image: 'my-car-project-image-iso'
    container_name: 'my-car-project-container'
    ports:
      - "3698:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5436/carProjectDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=carProjectDB
    ports:
      - "5436:5432"